apiVersion: v1
kind: Service
metadata:
  name: jwt-api-cluster
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jwt-api-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-api-cluster
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: jwt-api-cluster
  template:
    metadata:
      labels:
        app: jwt-api-cluster
    spec:
      containers:
        - name: jwt-api-cluster
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          env:
            - name: JWT_SECRET
              value: 1234
          ports:
            - containerPort: 8080
